-- Issue #229: timesheet clock times displaying as GMT instead of CST/CDT.
--
-- Run timesheet_gmt_backfill_verify.sql FIRST and review its output before running
-- this. This only corrects rows presumed to come from the auto clock-in/clock-out
-- buttons (sub-minute precision); manual admin entries are left untouched, since they
-- were typed in as intended local wall-clock times, not generated by the buggy
-- LocalDateTime.now().
--
-- IMPORTANT: run this ONCE, before deploying the TimeEntryService fix (PR #230) --
-- or at least before any new clock-in/out happens under the fixed code. Rows created
-- after the fix is live already store times the "corrected" way; running this against
-- them would shift them the wrong direction.
--
-- This does NOT auto-commit. Review the "UPDATE N" row count Postgres reports and
-- compare it to the row count from the verify script's first query before deciding
-- COMMIT vs ROLLBACK.

BEGIN;

UPDATE time_entries
SET clock_in  = (clock_in AT TIME ZONE 'America/Chicago') AT TIME ZONE 'UTC',
    clock_out = CASE WHEN clock_out IS NOT NULL
                     THEN (clock_out AT TIME ZONE 'America/Chicago') AT TIME ZONE 'UTC'
                     ELSE clock_out END,
    date      = (clock_in AT TIME ZONE 'America/Chicago')::date
WHERE date_trunc('minute', clock_in) <> clock_in
  AND (clock_out IS NULL OR date_trunc('minute', clock_out) <> clock_out);

-- Check the row count above matches the verify script's count, then either:
--   COMMIT;
-- or, if anything looks off:
--   ROLLBACK;
