ALTER TABLE room_types ADD COLUMN IF NOT EXISTS pet_friendly BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE extras ADD COLUMN IF NOT EXISTS description VARCHAR;
ALTER TABLE extras ADD COLUMN IF NOT EXISTS pet_friendly_only BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE reservations ADD COLUMN IF NOT EXISTS special_requests VARCHAR;
