ALTER TABLE room_types ADD COLUMN pet_friendly BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE extras ADD COLUMN description VARCHAR;
ALTER TABLE extras ADD COLUMN pet_friendly_only BOOLEAN NOT NULL DEFAULT FALSE;
