ALTER TABLE guests
    ADD COLUMN IF NOT EXISTS flagged      BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS flag_reason  VARCHAR,
    ADD COLUMN IF NOT EXISTS flagged_date TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS flagged_by   UUID REFERENCES employees (id);